[package]
name = "morse-code-converter"
version = "0.1.0"
edition = "2024"

[dependencies]
clokwerk = "0.4.0"
japanese = "0.1.2"
rand = "0.9.2"
ripmors = "0.1.0"
serialport = "4.7.2"
std-semaphore = "0.1.0"
wana_kana = "4.0.0"
